### PR TITLE
fix(cli): change model template to properly render array types

### LINKED ISSUE #1562: compile error in generated model ts file when using lb4 model
## Description / Steps to reproduce / Feature proposal
lb4 model
name it, etc
add a property of type array, and type object, using the cli

## Current Behavior
generated code is:
...
  @property({
    type: 'array',
    arrayType: object,

  })
  fields?: object[];

with the error (at least in vscode): Cannot find name 'object'. Did you mean 'Object'?  (the object after arrayType: has the squiggly line)
 
## Expected Behavior
no error in generated code ;-)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by shimks**
The CLI used to build the templates without the quotation marks around value for `arrayType`.
Also removes the ugly new lines generated through the template

The generated code before:
```ts
import {Entity, model, property} from '@loopback/repository';

@model()
export class Model extends Entity {
  
  @property({
    type: 'array',
    arrayType: string,
    
  })
  prop?: string[];
  
  @property({
    type: 'number',
    
  })
  propNumberTwo?: number;
  
  constructor(data?: Partial<Model>) {
    super(data);
  }
}
```

The generated code with this PR:
```ts
import {Entity, model, property} from '@loopback/repository';

@model()
export class Model extends Entity {
  @property({
    type: 'array',
    arrayType: 'string',
  })
  prop?: string[];

  @property({
    type: 'number',
  })
  propNumberTwo?: number;

  constructor(data?: Partial<Model>) {
    super(data);
  }
}
```

fixes #1562

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by jannyHou** [comment]
Oh wait...I misunderstood the original issue. 

The template decorates array property as 

```ts
@Property({
type: 'array',
arrayType: object,

})
fields?: object[];
```

While I think the correct signature should be
```ts
@Property.array({
itemType: Object
})
fields?: object[];
```

By using `@Property.array()`, the `itemType` field has to be a Type instead of a string, see [code](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/decorators/model.decorator.ts#L111)

**Comment by bajtos** [comment]
@shimks Could you please post two code snippets showing what was generated before and what code is generated after your change?

**Comment by shimks** [comment]
updated the main post with code example

File: packages/cli/generators/model/index.js [hunk 1]
```diff
@@ -234,6 +234,9 @@ module.exports = class ModelGenerator extends ArtifactGenerator {
 
       // Convert Type to include '' for template
       val.type = `'${val.type}'`;
+      if (val.arrayType) {
```
Comment (dhmlau) [inline packages/cli/generators/model/index.js]: do you mean to include this change in this PR because this PR is only supposed for model template change?

**Comment by raymondfeng** [comment]
`arrayType` is vague. Can we switch to something like `itemType`?

**Comment by shimks** [comment]
@raymondfeng I _think_ that discussion should be held over at #1570, where we may need to tweak it along with deciding how juggler property definition would look like.
