### PR TITLE
Juggler array

### LINKED ISSUE #1562: compile error in generated model ts file when using lb4 model
## Description / Steps to reproduce / Feature proposal
lb4 model
name it, etc
add a property of type array, and type object, using the cli

## Current Behavior
generated code is:
...
  @property({
    type: 'array',
    arrayType: object,

  })
  fields?: object[];

with the error (at least in vscode): Cannot find name 'object'. Did you mean 'Object'?  (the object after arrayType: has the squiggly line)
 
## Expected Behavior
no error in generated code ;-)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by shimks**
The property definition for arrays used to be defined this way:
```ts
{type: 'string', array: true}
// or
{type: String, array: true}
```

This does not match with the property definition of an array as the legacy juggler would define it. The property definition created by the `@property.array(String)` decorator can now look like this:
```ts
{type: 'array', itemType: String}
// @repository-json-schema also supports
{type: 'array', itemType: 'string'}
```

Related to #1508
Fixes #1562

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

File: packages/repository-json-schema/src/build-schema.ts [hunk 1]
```diff
@@ -36,68 +36,95 @@ export function getJsonSchema(ctor: Function): JSONSchema {
...
-    case 'boolean': {
-      wrapper = Boolean;
-      break;
-    }
-    default: {
-      throw new Error('Unsupported type: ' + type);
+export function stringTypeToWrapper(type: string | Function): Function {
+  if (typeof type === 'function') {
+    return type;
+  } else {
```
Comment (bajtos) [inline packages/repository-json-schema/src/build-schema.ts]: Please remove this `else` block to reduce indentation level and keep the changeset smaller.

```ts
if (typeof type === 'function') {
  return type;
}

type = type.toLowerCase();
let wrapper;
switch(type) {
// ...
```

File: packages/repository-json-schema/test/unit/build-schema.unit.ts [hunk 2]
```diff
@@ -8,10 +8,14 @@ import {isComplexType, stringTypeToWrapper, metaToJsonProperty} from '../..';
 
 describe('build-schema', () => {
   describe('stringTypeToWrapper', () => {
-    it('returns respective wrapper of number, string and boolean', () => {
+    it('returns respective wrapper of number, string, boolean, array, buffer, date and object', () => {
```
Comment (bajtos) [inline packages/repository-json-schema/test/unit/build-schema.unit.ts]: One (logical) assert per test - please refactor this test into a series of small test cases.

```ts
it('returns String for "string"', () => {
  expect(stringTypeToWrapper('string')).to.eql(String);
});

// ...
```

**Comment by bajtos** [comment]
IIRC, it was @raymondfeng's intention to design the metadata used by `@loopback/repository` from scratch to build the best user experience and don't be constrained by the definition language used by juggler. Having said that, I am not sure if `{type: 'string', array: true}` was an intentional design - I would personally use `{type: 'array', itemType: 'string'}`.

Please note that it's the responsibility of legacy-juggler-bridge to convert model & property definitions from LB4 format to whatever is required by juggler. See [`DefaultCrudRepository#setupPersistedModel()`](https://github.com/strongloop/loopback-next/blob/0601e37586bf38a94a205111fe09e07447948c10/packages/repository/src/repositories/legacy-juggler-bridge.ts#L112-L117).

To be honest, I don't know how to proceed with this pull request. Ideally, I'd like to hear from @raymondfeng on the array property format. On the other hand, he is away until next week and I don't want to block fixing #1562 because of that.

Is there a way how to fix the issue while preserving the current format for defining array properties?

File: packages/repository-json-schema/test/integration/build-schema.integration.ts [hunk 3]
```diff
@@ -258,124 +421,6 @@ describe('build-schema', () => {
...
-          @property()
-          badArr: string[];
-        }
-
-        expect(() => {
-          modelToJsonSchema(BadArray);
-        }).to.throw(/type is defined as an array/);
-      });
-
-      it('errors out if "@property.array" is given "Array" as parameter', () => {
```
Comment (virkt25) [inline packages/repository-json-schema/test/integration/build-schema.integration.ts]: Why are all these tests removed?

File: packages/repository/src/repositories/legacy-juggler-bridge.ts [hunk 4]
```diff
@@ -112,9 +112,16 @@ export class DefaultCrudRepository<T extends Entity, ID>
...
-    for (const p in definition.properties) {
-      properties[p] = Object.assign({}, definition.properties[p]);
-    }
+
+    // We need to convert PropertyDefinition into the definition that
+    // the juggler understands
+    Object.entries(definition.properties).forEach(([key, value]) => {
+      if (value.type === 'array' || value.type === Array) {
+        value = Object.assign({}, value, {type: [value.itemType]});
+        delete value.itemType;
```
Comment (virkt25) [inline packages/repository/src/repositories/legacy-juggler-bridge.ts]: Do we need to delete `value.itemType`? This will get deleted from the actual `definition.properties` Object IIRC -- in case it needs to be referenced again.

File: packages/repository-json-schema/test/integration/build-schema.integration.ts (hunk 3 above)
Comment (shimks) [reply packages/repository-json-schema/test/integration/build-schema.integration.ts]: These tests have been moved above for better organization, I'll quickly check if I actually removed any of the tests

File: packages/cli/generators/model/index.js [hunk 5]
```diff
@@ -204,18 +204,18 @@ module.exports = class ModelGenerator extends ArtifactGenerator {
...
-        if (TS_TYPES.includes(val.arrayType)) {
-          val.tsType = `${val.arrayType}[]`;
+        if (TS_TYPES.includes(val.itemType)) {
+          val.tsType = `${val.itemType}[]`;
         } else if (val.type === 'buffer') {
-          val.tsType = `Buffer[]`;
+          val.tsType = 'Buffer[]';
         } else {
-          val.tsType = `string[]`;
+          val.tsType = 'string[]';
```
Comment (jannyHou) [inline packages/cli/generators/model/index.js]: 'string[]' ---> 'String[]' ?

File: packages/repository/src/repositories/legacy-juggler-bridge.ts (hunk 4 above)
Comment (shimks) [reply packages/repository/src/repositories/legacy-juggler-bridge.ts]: Would it? I did want to avoid the manipulation of actual `definition.properties` by reassigning the variable `value` to what is a modified clone of `value` in line 120. Did I miss a step? This test case should cover it: https://github.com/strongloop/loopback-next/pull/1570/files#diff-328c8e879ea3a53d7fb50599f1c6a77eR121

File: packages/cli/generators/model/index.js (hunk 5 above)
Comment (shimks) [reply packages/cli/generators/model/index.js]: I know `string[]` works but does `String[]` work as well?

File: packages/repository-json-schema/src/build-schema.ts [hunk 6]
```diff
@@ -64,40 +83,55 @@ export function stringTypeToWrapper(type: string): Function {
...
-  }
-
-  if (typeof ctor === 'string') {
-    ctor = stringTypeToWrapper(ctor);
+  // tslint:disable-next-line:no-any
+  const propDef: JSONSchema = {};
+  let result: JSONSchema;
+  let propertyType = meta.type as string | Function;
+
+  if (isArrayType(propertyType) && meta.itemType) {
```
Comment (jannyHou) [inline packages/repository-json-schema/src/build-schema.ts]: hmm...any reason why using two different ways to assert the array type?
`isArrayType` vs `Array.isArray`

File: packages/cli/generators/model/index.js (hunk 5 above)
Comment (jannyHou) [reply packages/cli/generators/model/index.js]: sorry never mind :( I mixed it with the array type in juggler. `string[]` is correct.

Comment (jannyHou) [reply packages/cli/generators/model/index.js]: found a `String[]` on line https://github.com/strongloop/loopback-next/pull/1570/files#diff-328c8e879ea3a53d7fb50599f1c6a77eR98...I feel confused again 🤔

Comment (shimks) [reply packages/cli/generators/model/index.js]: I _think_ they both work 🤷‍♂️

File: packages/repository-json-schema/src/build-schema.ts (hunk 6 above)
Comment (shimks) [reply packages/repository-json-schema/src/build-schema.ts]: `isArrayType` essentially asserts whether given data corresponds to the Wrapper `Array` or the string 'array'

**Comment by jannyHou** [comment]
I believe this PR would fix issue https://github.com/strongloop/loopback-next/issues/1508 as well. The [comment](https://github.com/strongloop/loopback-next/pull/1570#issuecomment-408769639) from @bajtos covered all my thought. 

The signature `{type: 'array', itemType: 'string'}` looks good to me, so I would also like to know more about how we decided to take the other signature `{type: 'string', array: true}`.

File: packages/repository/src/repositories/legacy-juggler-bridge.ts (hunk 4 above)
Comment (virkt25) [reply packages/repository/src/repositories/legacy-juggler-bridge.ts]: nvm, the `Object.assign` creates a new reference. This is fine.
