### PR TITLE
fix(cli): set glob options to support windows paths with special chars

### LINKED ISSUE #1943: lb4 export-api-def results in AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist:
## Description / Steps to reproduce / Feature proposal

I would like to generate the openapi.json or a swagger definition in any kind. But templates are missing.

## Current Behavior

$ lb4 export-api-def
? Project description: nma-services-swagger
? Project root directory: client-swagger
? Application class name: tests
? Select features to enable in the project Enable tslint, Enable prettier, Enable mocha, Enable loopbackBuild, Enable vs
code, Enable repositories, Enable services
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\generators\project\templates\**\*
    at EditionInterface.exports.copy (D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\node_modules\mem-fs-editor\lib\actions\copy.js:48:3)
    at EditionInterface.module.exports [as copyTpl] (D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:29:8)
    at AppGenerator.scaffold (D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\lib\project-generator.js:195:13)
    at AppGenerator.scaffold (D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\generators\app\index.js:109:18)
    at Object.<anonymous> (D:\Users\myname\AppData(Roaming)\npm\node_modules\@loopback\cli\node_modules\yeoman-generator\lib\index.js:424:27)

## Expected Behavior

a file is generated that contains the swagger / openapi definition.

### PR DESCRIPTION
**Pull request by raymondfeng**
Fix #1943 

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

File: packages/cli/generators/controller/index.js [hunk 1]
```diff
@@ -236,13 +236,7 @@ module.exports = class ControllerGenerator extends ArtifactGenerator {
...
       debug(`Copying artifact to: ${dest}`);
     }
-    this.fs.copyTpl(
-      source,
-      dest,
-      this.artifactInfo,
-      {},
-      {globOptions: {dot: true}},
-    );
+    this.copyTpl(source, dest, this.artifactInfo);
```
Comment (bajtos) [inline packages/cli/generators/controller/index.js]: Can we avoid abbreviations in our names please? I am proposing `copyTemplate` or `copyTemplates` depending on whether this method copies a single or multiple templates.

Comment (raymondfeng) [reply packages/cli/generators/controller/index.js]: Renamed to `copyTemplatedFiles`
