### PR TITLE
fix: re-export generateUniqueId in index.ts

### LINKED ISSUE #6767: unable to import "generateUniqueId" from @loopback/core
## Steps to reproduce

As per the [Binding documentation](https://loopback.io/doc/en/lb4/Binding.html):

```ts
import {generateUniqueId} from '@loopback/core';
```

## Current Behavior

```
import generateUniqueId
'generateUniqueId' is declared but its value is never read.ts(6133)
Module '"../node_modules/@loopback/core/dist"' has no exported member 'generateUniqueId'.ts(2305)
```

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by achrinza**
fixes #6767

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

File: packages/context/src/binding-key.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
 // This file is licensed under the MIT License.
 // License text available at https://opensource.org/licenses/MIT
 
-import {generateUniqueId} from './unique-id';
+import {generateUniqueId} from '.';
```
Comment (raymondfeng) [inline packages/context/src/binding-key.ts:6]: We should try to avoid import local items from the `index` as it may introduce circular `import`.

File: packages/core/src/application.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ import {
   JSONObject,
   Provider,
   registerInterceptor,
-  ValueOrPromise,
+  ValueOrPromise
```
Comment (raymondfeng) [inline packages/core/src/application.ts:19]: This should be reverted.

File: packages/core/src/application.ts [hunk 3]
```diff
@@ -27,7 +27,7 @@ import {CoreBindings, CoreTags} from './keys';
 import {
   asLifeCycleObserver,
   isLifeCycleObserverClass,
-  LifeCycleObserver,
+  LifeCycleObserver
```
Comment (raymondfeng) [inline packages/core/src/application.ts:30]: This should be reverted.

**Review by raymondfeng — APPROVED** [review]
