### PR TITLE
fix(cli): fix prompt for base repository class

### LINKED ISSUE #2429: CLI repository does not ask for base repository
## Description / Steps to reproduce / Feature proposal
Due to an last minute error in the merge, the prompt that ask for the base repository class is not showed to the user on interactive mode.
This change was introduced in #2149 

## Current Behavior
After ask for datasource and model, the CLI does not prompt for the repository base class and uses the default value "DefaultCrudRepository"

## Expected Behavior
After ask for datasource and model, the CLI must prompt for the repository base class.

Fix is below. 
`when: this.artifactInfo.repositoryBaseClass === undefined` is never undefined and for this reason prompt is not showed.

```
--- a/packages/cli/generators/repository/index.js
+++ b/packages/cli/generators/repository/index.js
@@ -415,9 +415,11 @@ module.exports = class RepositoryGenerator extends ArtifactGenerator {
         type: 'list',
         name: 'repositoryBaseClass',
         message: PROMPT_BASE_REPOSITORY_CLASS,
-        when: this.artifactInfo.repositoryBaseClass === undefined,
         choices: availableRepositoryList,
-        default: availableRepositoryList[0],
+        default:
+          this.artifactInfo.repositoryBaseClass === undefined
+            ? availableRepositoryList[0]
+            : this.options.repositoryBaseClass,
       },
     ])
       .then(props => {

```
#

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by gczobel-f5**
fix #2429

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

File: packages/cli/generators/repository/index.js [hunk 1]
```diff
@@ -415,9 +415,11 @@ module.exports = class RepositoryGenerator extends ArtifactGenerator {
         type: 'list',
         name: 'repositoryBaseClass',
         message: PROMPT_BASE_REPOSITORY_CLASS,
-        when: this.artifactInfo.repositoryBaseClass === undefined,
         choices: availableRepositoryList,
-        default: availableRepositoryList[0],
+        default:
```
Comment (jannyHou) [inline packages/cli/generators/repository/index.js]: @gczobel-f5 I feel the logic here has conflict with the code that [sets default value for option repositoryBaseClass](https://github.com/strongloop/loopback-next/blob/92e6f8063c5930acc7193c1a832fb542eec6d83e/packages/cli/generators/repository/index.js#L186-L190) and [assigns the options's value to artifactInfo](https://github.com/strongloop/loopback-next/blob/92e6f8063c5930acc7193c1a832fb542eec6d83e/packages/cli/generators/repository/index.js#L404-L422)
Like you said in https://github.com/strongloop/loopback-next/issues/2429, `this.artifactInfo.repositoryBaseClass` will never be undefined....

Comment (gczobel-f5) [reply packages/cli/generators/repository/index.js]: You are right. I returned the default to the original option.

**Comment by gczobel-f5** [comment]
@jannyHou @bajtos @raymondfeng Hi, this small bug is already fixed. Can you merge it, please?
