### PR TITLE
fix: user profile to principal

### LINKED ISSUE #3766: authorization: workaround userToPrinciple replaces expected securityId
# Steps to reproduce

I tried to write a custom `Authorizer` and just logged the `AuthorizationContext` to console. The `securityId` does not contain the expected value.

## Current Behavior

https://github.com/strongloop/loopback-next/blob/7bf6f12f1da721a78071904fa02252577f4d1cba/packages/authorization/src/authorize-interceptor.ts#L155-L164

The provided `securityId` of an user gets replaced by user.id

## Expected Behavior

As UserProfile of `@loopback/security` is now also `Principal`, there is no need for this convertion anymore. The provided `securityId` should be used as provided. The workaround seems not necessary anymore.

## Additional information

```
$ npm ls --prod --depth 0 | grep loopback
+-- @loopback/authentication@3.0.1
+-- @loopback/authorization@0.3.0
+-- @loopback/boot@1.5.6
+-- @loopback/booter-lb3app@1.3.0
+-- @loopback/context@1.23.0
+-- @loopback/core@1.10.2
+-- @loopback/extension-health@0.2.6
+-- @loopback/openapi-v3@1.9.7
+-- @loopback/repository@1.14.0
+-- @loopback/rest@1.19.0
+-- @loopback/rest-explorer@1.3.7
+-- @loopback/service-proxy@1.3.6
+-- loopback@3.2.1
+-- loopback-boot@3.3.0
+-- loopback-component-passport@3.0.0
+-- loopback-connector-mongodb@5.0.0
+-- loopback-connector-mysql@5.4.2
+-- loopback-connector-postgresql@3.7.0
+-- loopback-connector-rest@2.1.0
+-- loopback-datasource-juggler@3.2.0
```

### PR DESCRIPTION
**Pull request by jannyHou**
Fixes #3766 and #3707 

Since PR https://github.com/strongloop/loopback-next/pull/3796 is created earlier I would like to respect @derdeka 's contribution, feel free to take code from this PR to save your time on adding tests/code refactor.

My only concern for #3796 is explained in [comment](https://github.com/strongloop/loopback-next/pull/3796#discussion_r328143044), after fixing it we can land it, then see if my PR still needed(improve #3796 or close it).

### CODE REVIEW

File: packages/authorization/src/util.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
+import {Principal, securityId, UserProfile} from '@loopback/security';
+
+// This is a workaround before we specify `TypedPrincipal` instead of
+// `Principal` for the principals in the authorization context.
```
Comment (jannyHou) [inline packages/authorization/src/util.ts]: The change will be addressed as part of https://github.com/strongloop/loopback-next/issues/2246 or as a follow-up story after the spike done.

File: packages/authorization/src/util.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+ * whether a user has access to a certain resource.
+ *
+ * The builder function:
+ * - preserves all the fields from user profile
+ * - specifies 'USER' as type
+ * - assign the value of `securityId` to name if it's missing in the
+ * user profile
+ * @param user The user profile passed from `@loopback/authentication`.
+ */
+export function userProfileToPrincipalBuilder(user: UserProfile): Principal {
```
Comment (raymondfeng) [inline packages/authorization/src/util.ts]: Maybe name it as `createPrincipalFromUserProfile`?
