### PR TITLE
[WIP] Fix 3965

### LINKED ISSUE #3965: Better diagnostics with CLI command `lb4 repository`
## Steps to reproduce

Edit one of your datasource JSON files to contain a trailing comma on the last key/value pair (or any other violation of JSON standards).
Run `lb4 repository` and observe the uncaught error.  Notice that the error explains that a JSON parsing error occurred, but says it happened in anonymous JSON, instead of naming the problematic file.

## Current Behavior

An error is thrown, indicating that JSON parsing failed, but not which datasource file is to blame:
```events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token } in JSON at position 198
    at JSON.parse (<anonymous>)
    at Object.exports.isConnectorOfType (/usr/local/lib/node_modules/@loopback/cli/lib/utils.js:510:28)
    at datasourcesList.filter.item (/usr/local/lib/node_modules/@loopback/cli/generators/repository/index.js:258:28)
    at Array.filter (<anonymous>)
    at RepositoryGenerator.promptDataSourceName (/usr/local/lib/node_modules/@loopback/cli/generators/repository/index.js:256:50)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:404:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

## Expected Behavior

Desired outcome would be that the name of the file containing the illegally-formatted JSON would be listed, so the developer would quickly be able to fix the file.

Something more like:
```
SyntaxError: Unexpected token } in JSON at  position 198
    at JSON.parse ("src/datasources/{name-of-your-datasource}.datasource.json")
```
_carry on with stack trace here_

## Link to reproduction sandbox

I tried to follow https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs instructions by forking + branching, then committing a change to one of the datasources in the To Do example.  The change consists only of adding a trailing comma to the last entry in the src/db.datasource.json file so that it violates JSON formatting rules.

## Additional information

jons-mbp:\~/iar/api $ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 10.15.1
jons-mbp:\~/iar/api $ npm ls --prod --depth 0 | grep loopback
├── @loopback/authentication@3.0.1
├── @loopback/boot@1.5.6
├── @loopback/context@1.23.0
├── @loopback/core@1.10.2
├── @loopback/openapi-v3@1.9.7
├── @loopback/repository@1.14.0
├── @loopback/rest@1.19.0
├── @loopback/rest-explorer@1.3.7
├── @loopback/service-proxy@1.3.6
├── loopback-connector-db2@2.2.0
├── loopback-connector-mysql@5.4.2
├── loopback-connector-rest@3.5.0
jons-mbp:~/iar/api $

### PR DESCRIPTION
**Pull request by ibmjm**
Adds better output when failing to parse a datasource file for any reason, by including the filename of the datasource in question.

Fixes #3965

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [x] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by raymondfeng** [comment]
@ibmjm I have squashed all commits in your PR into one and fixed the commit message to comply with our conventional commit rules. See https://loopback.io/doc/en/lb4/submitting_a_pr.html

**Comment by ibmjm** [comment]
> @ibmjm I have squashed all commits in your PR into one and fixed the commit message to comply with our conventional commit rules. See https://loopback.io/doc/en/lb4/submitting_a_pr.html

Thank you Raymond.  I did read the guide to submitting PRs prior to creating mine; which rule did I breach?

**Comment by raymondfeng** [comment]
@ibmjm See https://loopback.io/doc/en/lb4/submitting_a_pr.html#1-commits-to-local-repository

**Comment by raymondfeng** [comment]
https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines

File: packages/cli/lib/utils.js [hunk 1]
```diff
@@ -471,6 +471,7 @@ exports.getDataSourceConnectorName = function(datasourcesDir, dataSourceClass) {
     jsonFileContent = JSON.parse(fs.readFileSync(datasourceJSONFile, 'utf8'));
   } catch (err) {
     debug(`Error reading file ${datasourceJSONFile}: ${err.message}`);
+    err.message = `Cannot load ${datasourceJSONFile}: ${err.message}`;
```
Comment (raymondfeng) [inline packages/cli/lib/utils.js]: Personally I would like to have a new Error that wraps the original one. It's easy to do so in Java, such as `new MyError(anotherError)`, but not in JavaScript :-(.

Comment (raymondfeng) [reply packages/cli/lib/utils.js]: Something like https://javascript.info/custom-errors#wrapping-exceptions. Maybe we should introduce a helper in LB4.

Comment (ibmjm) [reply packages/cli/lib/utils.js]: My first attempt to provide an error message that included the filename of the datasource where the failure originated, was indeed to throw a new Error.  However, @bajtos pointed out that we'd lose the stack trace by doing that -- hence the modification to the original Error's message.

Comment (raymondfeng) [reply packages/cli/lib/utils.js]: I'm fine with your fix for now.

Comment (dreamdevil00) [reply packages/cli/lib/utils.js]: > Personally I would like to have a new Error that wraps the original one. It's easy to do so in Java, such as `new MyError(anotherError)`, but not in JavaScript :-(.

Have you considered using [verror](https://www.npmjs.com/package/verror)?
