### PR TITLE
fix(cli): reorder where and body in CLI template for updateAll

### LINKED ISSUE #1521: [CLI] - lb4 controller generator misplaced arguments on updateAll
## Description / Steps to reproduce / Feature proposal
Having upgraded to @looopback/cli 0.17.0 and now 0.18.1 and created a new project and a model and a repository.

## Current Behavior

run `lb4 controller` on the  project generates an error on the following line 
` return await this.fruitsRepository.updateAll(where, obj); `

Previous version of the `lb4 controller` CLI command offered this template, however something might have changed in the core but was not synced with the generated file.

The code in the legacy-juggler-bridge is as follows
`    updateAll(data: Partial<T>, where?: Where, options?: Options): Promise<number>; `

## Expected Behavior
So, we have to fix the line manually to be compliance with the implementation. 
 `    return await this.fruitsRepository.updateAll(obj, where); `

The CLI generator for controller has been fixed, I will be making a pull request!. Please advise if I can do it, it is a simple change and I would like to try it out :-)

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by shimks**
Current way the call is made with updateAll in the CRUD CLI template:
`return await this.<%= repositoryNameCamel %>.updateAll(where, obj);`

Signature of `updateAll`:
```ts
  updateAll(
    data: Partial<T>,
    where?: Where,
    options?: Options,
  ): Promise<number>
```

The where object and the body need to be switched around

fixes #1521 

## Checklist

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Comment by bajtos** [comment]
+1 for changing the order of controller method arguments too, and also making the `where` argument of the controller method optional in TypeScript. The way how it is annotated is making the argument required as far as the REST layer is concerned.

File: packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs [hunk 1]
```diff
@@ -24,26 +23,26 @@ export class <%= className %>Controller {
...
   }
 
   @patch('<%= httpPathName %>')
   async updateAll(
-    @param.query.string('where') where: Where,
     @requestBody() obj: <%= modelName %>
+    @param.query.string('where') where?: Where,
   ): Promise<number> {
-    return await this.<%= repositoryNameCamel %>.updateAll(where, obj);
+    return await this.<%= repositoryNameCamel %>.updateAll(obj, where);
```
Comment (raymondfeng) [inline packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs]: Should the obj to be `Partial<<%= modelName %>>`?

Comment (shimks) [reply packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs]: Yeah it should be, but from what i remember of #1179, this should incorrectly generate the schema, so it's something that should probably be avoided until it can be fixed

Comment (raymondfeng) [reply packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs]: I see. It's probably time to introduce a `@type` decorator.

File: docs/site/Controller-generator.md [hunk 2]
```diff
@@ -114,25 +114,25 @@ export class TodoController {
...
     return await this.todoRepository.find(filter);
   }
 
   @patch('/todos')
   async updateAll(
-    @param.query.string('where') where: Where,
     @requestBody() obj: Todo,
+    @param.query.string('where') where?: Where,
   ): Promise<number> {
     return await this.todoRepository.updateAll(where, obj);
```
Comment (virkt25) [inline docs/site/Controller-generator.md]: This should be updated to be `obj, where`?
