### PR TITLE
fix: extend test timeout for windows

### LINKED ISSUE #4425: npm test hangs infinitly on windows
## Steps to reproduce

- check out loopback-next repo
- `npm install`
- `npm test` or `DEBUG=mocha:* npm test`

## Current Behavior

Many tests are executed - one test does not end. `npm test` never ends and runs infinitely. 
Tried with `cmd`, `powershell` and git `bash`.

> mocha:runner run suite app-generator (SLOW) +17ms

^^^^^^is the last logged console output.

## Expected Behavior

`npm test` should end successfully or with some error message.

## Additional information

Windows 10 Pro ver 1909
node v10.15.3
Docker version 19.03.4, build 9013bf5
@loopback/cli version: 1.28.1

when executing `DEBUG=mocha:* npm test` these are the last few log messages:
```bash
..  mocha:runner run suite TodoApplication +60ms
  mocha:runnable timeout 30000 +11s
  mocha:runnable timeout 30000 +2s
...  mocha:runnable timeout 30000 +25ms
..  mocha:runner run suite TodoApplication when dealing with a single persisted todo +3s
........  mocha:runner run suite GeoLookupService +71ms
.  mocha:runner run suite TodoController +18ms
  mocha:runner run suite TodoController createTodo +0ms
..  mocha:runner run suite TodoController findTodoById +37ms
.  mocha:runner run suite TodoController findTodos +14ms
...  mocha:runner run suite TodoController replaceTodo +36ms
.  mocha:runner run suite TodoController updateTodo +12ms
.  mocha:runner run suite TodoController deleteTodo +11ms
.  mocha:runner run suite app-generator (SLOW) +17ms
  mocha:runnable timeout 60000 +235ms
```

### PR DESCRIPTION
**Pull request by dougal83**
Give windows extra time to complete tests
Fixes #4425

fix: cleanup tilde-path-app post test …
ensure test app is remove afterward
Fixes #4652

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by dougal83** [comment]
@derdeka If you have time, could you please run tests against this PR?

File: packages/cli/test/integration/generators/app.integration.js [hunk 1]
```diff
@@ -295,7 +295,12 @@ describe('app-generator with tilde project path', () => {
     // eslint-disable-next-line no-invalid-this
     this.timeout(30 * 1000);
 
-    process.chdir(sandbox);
+    // If the test runs outside $home directory
+    if (process.env.CI && !process.env.DEBUG) {
+      process.chdir(sandbox);
+    } else {
+      process.chdir(rootDir);
+    }
```
Comment (dougal83) [inline packages/cli/test/integration/generators/app.integration.js]: @agnes512 Does this look reasonable?  I had to do this for CI test but I'm not sure how that works.  I've also dropped a clause to compare the sandbox path from L266.

File: packages/cli/test/integration/generators/app.integration.js [hunk 2]
```diff
@@ -295,7 +295,12 @@ describe('app-generator with tilde project path', () => {
     // eslint-disable-next-line no-invalid-this
     this.timeout(30 * 1000);
 
-    process.chdir(sandbox);
+    // If the test runs outside $home directory
+    if (process.env.CI && !process.env.DEBUG) {
```
Comment (bajtos) [inline packages/cli/test/integration/generators/app.integration.js]: I am little bit concerned about duplicating the logic deciding whether to use `sandbox` or `rootDir`, because if we change the original condition [on line 266](https://github.com/strongloop/loopback-next/blob/9aba52e59c80830dd0871c4a087b90ec2aa21db2/packages/cli/test/integration/generators/app.integration.js#L266), then how are we going to ensure this copy is updated as well?

If we want to change to a different directory, then let's introduce a new variable set to true/false depending on whether the condition on line 266 was triggered or not.

Having said that, I am not sure if changing the directory to `rootDir` is the right thing to do, see my comment below.

File: packages/cli/test/integration/generators/app.integration.js (hunk 1 above)
Comment (bajtos) [reply packages/cli/test/integration/generators/app.integration.js]: Hmm, I find this suspicious. On the next line, we are running a cleanup script in the `sandbox` directory:

https://github.com/strongloop/loopback-next/blob/9aba52e59c80830dd0871c4a087b90ec2aa21db2/packages/cli/test/integration/generators/app.integration.js#L304

Does the behavior of `run-clean` depend on the current working directory? If it does not, then perhaps we can get rid of this first `process.chdir` entirely, and keep the last `chdir(cwd)` only?

```ts
   after(function() {
    // Increase the timeout to accommodate slow CI build machines
    // eslint-disable-next-line no-invalid-this
    this.timeout(30 * 1000);

    build.clean(['node', 'run-clean', sandbox]);
    process.chdir(cwd);
  });
```

File: packages/cli/test/integration/generators/app.integration.js (hunk 2 above)
Comment (dougal83) [reply packages/cli/test/integration/generators/app.integration.js]: > If we want to change to a different directory, then let's introduce a new variable set to true/false depending on whether the condition on line 266 was triggered or not.

New variable utilised.

File: packages/cli/test/integration/generators/app.integration.js (hunk 1 above)
Comment (dougal83) [reply packages/cli/test/integration/generators/app.integration.js]: This appears to be a special case for tilde check. We are using sandbox that is outside the code's project root. Not setting the `process.chdir` gives for example: `Skipping /home/dev/workspace/loopback-next/sandbox/tilde-path-app as it is not inside the project root directory.`

**Comment by dougal83** [comment]
`npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/@commitlint/cli/-/cli-8.3.5.tgz`

Usually Cloudflare?  Will manually restart test later.

**Comment by dougal83** [comment]
> The `chdir` fix is not pretty, but as long as it works, I think it's best to land it now and then clean it up later (if at all).

Amen. 🙏
