### PR TITLE
fix(cli): enforce an empty object on connectors with no settings

### LINKED ISSUE #1697: Cannot create a kv-memory datasource using `lb4 datasource`
## Description / Steps to reproduce / Feature proposal

Create an LB4 app, e.g. via `lb4 app`.

Try to create a datasource backed by `kv-memory` connector by running `lb4 datasource`.

## Current Behavior

The process crashes.

```
$ lb4 datasource
? Datasource name: keyvalue
? Select the connector for keyvalue: In-memory key-value connector (supported by StrongLoop)
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at DataSourceGenerator.promptConnectorConfig (/Users/bajtos/src/loopback/next/packages/cli/generators/datasource/index.js:159:12)
    at Object.<anonymous> (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/bajtos/src/loopback/next/packages/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/bajtos/src/loopback/next/packages/cli/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/bajtos/src/loopback/next/packages/cli/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

## Expected Behavior

The datasource is created.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by marioestradarosa**
It seems that the connector in mention doesn't have a settings property, thus the code was not enforcing a {} object but rather an undefined, which caused the generator to fail. I am assuming this connector doesn't need the settings property, if that's the case , this PR successfully fixes the error. If not, then I believe we need to add the settings property also.

fix #1697

## Checklist

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

File: packages/cli/generators/datasource/index.js [hunk 1]
```diff
@@ -150,11 +150,13 @@ module.exports = class DataSourceGenerator extends ArtifactGenerator {
...
     // Check to make sure connector is from connectors list (not custom)
-    const settings = connectors[this.artifactInfo.connector]
-      ? connectors[this.artifactInfo.connector]['settings']
-      : {};
-
+    const settings =
+      connectors[this.artifactInfo.connector] &&
+      connectors[this.artifactInfo.connector]['settings']
+        ? connectors[this.artifactInfo.connector]['settings']
+        : {};
```
Comment (raymondfeng) [inline packages/cli/generators/datasource/index.js]: It can be simplified as:
```ts
const settings =
      (connectors[this.artifactInfo.connector] &&
      connectors[this.artifactInfo.connector]['settings']) || {};
```

Comment (marioestradarosa) [reply packages/cli/generators/datasource/index.js]: good example of using javascript sintax to simplify it. 👍

**Comment by marioestradarosa** [comment]
@bajtos  I will test the capability of merging with the **big** green button now.

**Comment by bajtos** [comment]
Thank you @marioestradarosa for fixing the bug 🎉
