### PR TITLE
fix(metadata): refine clone of decoration spec

### LINKED ISSUE #1182: `@repository(Model, datasource)` will not work properly
## Description / Steps to reproduce / Feature proposal

Add a new controller with the following code:
```ts
import {
  DataSourceConstructor,
  repository,
  EntityCrudRepository,
  model,
  property,
  Entity,
} from '@loopback/repository';
import {post, get, requestBody} from '@loopback/rest';

const db = new DataSourceConstructor({
  name: 'db',
  connector: 'memory',
});

@model()
export class Todo extends Entity {
  @property({id: true})
  id: number;
}

export class TodoController {
  @repository(Todo, db)
  todoRepo: EntityCrudRepository<Todo, typeof Todo.prototype.id>;

  @post('/todo')
  async post(@requestBody() todo: Todo) {
    return await this.todoRepo.create(todo);
  }

  @get('/todo')
  async get() {
    return await this.todoRepo.find();
  }
}
```

## Current Behavior

Going to one of the endpoints when the app is running will cause a timeout.

## Expected Behavior

The endpoint should be able to call its generated repo's method.

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

### PR DESCRIPTION
**Pull request by raymondfeng**
See https://github.com/strongloop/loopback-next/issues/1182. The root
cause is that DataSource instances are cloned incorrectly.

Fixes #1182

## Checklist

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `packages/example-*` were updated

### CODE REVIEW

File: packages/repository/test/unit/decorator/repository.ts [hunk 1]
```diff
@@ -85,20 +85,21 @@ describe('repository decorator', () => {
...
         @repository(Note, ds)
-        public noteRepo: Repository<Note>,
+        public noteRepo: EntityCrudRepository<Note, number>,
       ) {}
     }
     ctx.bind('controllers.Controller3').toClass(Controller3);
-    const myController = await ctx.get<MyController>('controllers.Controller3');
+    const myController = await ctx.get<Controller3>('controllers.Controller3');
     expect(myController.noteRepo).to.be.not.null();
+    await myController.noteRepo.find();
```
Comment (shimks) [inline packages/repository/test/unit/decorator/repository.ts]: Is there a better way to test for this? In #1182, the function hangs after it gets called. If there's a way to test that calling the function doesn't result in it being stuck, I'd be happy.

**Comment by shimks** [comment]
Thanks for the quick fixup Raymond! Could you explain how having metadata (datasource) shallowly cloned results in all calls to repository functions like `find` result in them hanging?

**Comment by raymondfeng** [comment]
> Could you explain how having metadata (datasource) shallowly cloned results in all calls to repository functions like find leave them hanging?

In your case, the repository is created from the model and dataSource during the dependency injection. But the dataSource is cloned and its `connecting` state is `true` when clone happens. The cloned dataSource object will always have `connecting=true` and all CRUD operations hang because `connected` is not `true`.
