### PR TITLE
[WIP] fix: add class name separation to multiple class names output

### LINKED ISSUE #3350: Missing whitespace in lb4 repository command last line output when selecting multiple models
# Description/Steps to reproduce
1- Create a new project and enable repositories
```cmd
lb4
? Project description: loopback
? Project root directory: loopback
? Application class name: LoopbackApplication
? Select features to enable in the project Enable repositories
```
2- Move to the proyect folder and add two models (with any name and default values would do)
```cmd
cd loopback
lb4 model
? Model class name: Animal
? Please select the model base class Entity (A persisted model with an ID)
? Allow additional (free-form) properties? No

lb4 model
? Model class name: Pet
? Please select the model base class Entity (A persisted model with an ID)
? Allow additional (free-form) properties? No
```

3- Add any datasource with default values
```cmd
lb4 datasource
? Datasource name: db
? Select the connector for db: In-memory db (supported by StrongLoop)
? window.localStorage key to use for persistence (browser only): 
? Full path to file for persistence (server only): 
```
4- Add a repository for both entities
```cmd
lb4 repository
? Please select the datasource DbDatasource
? Select the model(s) you want to generate a repository Animal, Pet
? Please select the repository base class DefaultCrudRepository (Legacy juggler bridge)
? Please enter the name of the ID property for Animal: id
? Please enter the name of the ID property for Pet: id
   create src/repositories/animal.repository.ts
   create src/repositories/pet.repository.ts
   update src/repositories/index.ts
   update src/repositories/index.ts

Repositories AnimalRepositoryPetRepository was created in src/repositories/
```

# Link to reproduction sandbox

The issue is before launching the app

# Expected result

Last line should be something like the following:
```cmd
Repositories AnimalRepository PetRepository created in src/repositories/
```
instead of
```cmd
Repositories AnimalRepositoryPetRepository was created in src/repositories/
```

# Additional information

```
node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 11.15.0```
```cmd
npm ls --prod --depth 0 | grep loopback
loopback@1.0.0 /home/charly/repos/loopback/loopback
├── @loopback/boot@1.4.4
├── @loopback/context@1.20.2
├── @loopback/core@1.8.5
├── @loopback/openapi-v3@1.7.0
├── @loopback/repository@1.8.2
├── @loopback/rest@1.16.3
└── @loopback/rest-explorer@1.2.5
```

### PR DESCRIPTION
**Pull request by Charly6596**
This commit adds a character defined in artifact-generator.js to be used when the output contains
multiple class names

The idea was to just add a comma as separator where the class names are merged, but at the end of the process, the class names variable is passed to a function in `artifact-generator.js`, `toClassName`, that transforms it to a PascalCaseName, removing any kind of invalid characters for a class name (whitespaces and commas included)
So the solution I've thought of is to apply that function for each class, instead of to every class at once

This is a work in progress and I'd appreciate if someone could help me with this, I won't be able to work on this anytime soon. And of course, any kind of feedback is appreciated!

fixes #3350

## TODO:
- [ ] Formatting tests aren't passing, I'd appreciate if someone can help with that
- [ ] Also have to update this branch, since at the moment of writing this is 73 commits behind the master branch

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

File: packages/cli/lib/artifact-generator.js [hunk 1]
```diff
@@ -131,12 +134,22 @@ module.exports = class ArtifactGenerator extends BaseGenerator {
...
 
+      const classes = this.artifactInfo.name.split(this.classNameSeparator);
+      let classesOutput = '';
+
+      classes.forEach((c, i) => {
+        classesOutput +=
+          i + 1 === classes.length // if last element
+            ? utils.toClassName(c)
+            : utils.toClassName(c) + this.classNameSeparator;
+      });
```
Comment (raymondfeng) [inline packages/cli/lib/artifact-generator.js]: This can be simplified as follows:
```ts
const classesOutput = this.artifactInfo.name.split(this.classNameSeparator)
  .map(utils.toClassName)
  .join(this.classNameSeparator);
```

File: packages/cli/lib/artifact-generator.js [hunk 2]
```diff
@@ -177,7 +190,7 @@ module.exports = class ArtifactGenerator extends BaseGenerator {
       this.artifactInfo.indexesToBeUpdated.length === 0
     ) {
       this.artifactInfo.indexesToBeUpdated = [
-        {dir: this.artifactInfo.outDir, file: this.artifactInfo.outFile},
+        { dir: this.artifactInfo.outDir, file: this.artifactInfo.outFile },
```
Comment (raymondfeng) [inline packages/cli/lib/artifact-generator.js]: Please revert the format change or use `npm run prettier:fix` to fix it.

File: packages/cli/lib/artifact-generator.js [hunk 3]
```diff
@@ -70,13 +73,13 @@ module.exports = class ArtifactGenerator extends BaseGenerator {
...
         chalk.red('>>> ') +
-          `Underscores _ in the class name will get removed: ${this.artifactInfo.name}`,
+        `Underscores _ in the class name will get removed: ${this.artifactInfo.name}`,
       );
     }
     if (this.artifactInfo.name.match(/[\u00C0-\u024F\u1E00-\u1EFF]/)) {
       this.log(
         chalk.red('>>> ') +
-          `Accented chars in the class name will get replaced: ${this.artifactInfo.name}`,
+        `Accented chars in the class name will get replaced: ${this.artifactInfo.name}`,
```
Comment (raymondfeng) [inline packages/cli/lib/artifact-generator.js]: Please revert the format change or use `npm run prettier:fix` to fix it.

**Comment by raymondfeng** [comment]
Please also follow https://loopback.io/doc/en/lb4/submitting_a_pr.html to fix the commit log issue.

**Comment by raymondfeng** [comment]
@Charly6596 I was able to push some fixes back to your repo.
